version: 2
updates:
  - package-ecosystem: pip
    directory: "/requirements.txt"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: "[Dependency] "
