name: 'Submitty PR Title Check'
on:
  pull_request:
    # check when PR
    # * is created,
    # * title is edited, and
    # * new commits are added (to ensure failing title blocks merging)
    types: [ opened, reopened, edited, synchronize ]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: '(\[(Bugfix|Feature|Refactor|Testing|Documentation)\] .{2,40}$|\[(DevDependency|Dependency)\] .{2,70})$'
