name: Python Unit Tests

on: [push]

jobs:
  run-unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Python Dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Run Unit Tests
        run: |
          cd tests/unittest
          sudo python3 -m unittest discover
