name: Test Lichen Integration

on: [push]

jobs:
  test-lichen:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Lichen
        run: |
          sudo bash ./tests/integration/setup.sh
      - name: Run Integration Tests
        run: |
          cd /usr/local/submitty/GIT_CHECKOUT/Lichen/tests/integration
          sudo python3 -m unittest discover
